import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Anime Figure - Ronin',
    category: 'Anime Collectibles',
    price: 129.99,
    description: 'A highly detailed 1/7 scale figure of a wandering ronin from the acclaimed anime series "Shadows of Edo". Perfect for any collector.',
    images: ['https://picsum.photos/seed/ronin/800/800', 'https://picsum.photos/seed/ronin2/800/800', 'https://picsum.photos/seed/ronin3/800/800'],
    specifications: {
      Material: 'PVC, ABS',
      Height: '25cm',
      'Release Date': 'Q3 2024',
    },
    stock: 15,
  },
  {
    id: '2',
    name: 'Kaiju Vinyl Toy',
    category: 'Anime Collectibles',
    price: 89.99,
    description: 'A limited edition vinyl toy of the iconic kaiju "Giga-lizard". Features a retro-inspired design and vibrant colors.',
    images: ['https://picsum.photos/seed/kaiju/800/800', 'https://picsum.photos/seed/kaiju2/800/800'],
    specifications: {
      Material: 'Soft Vinyl',
      Height: '22cm',
      'Edition Size': '500',
    },
    stock: 30,
  },
  {
    id: '3',
    name: 'Galactic Empire Helmet Replica',
    category: 'Movie Memorabilia',
    price: 499.99,
    description: 'A 1:1 scale replica of the standard issue helmet for the Galactic Empire\'s elite soldiers. Made with high-quality materials and a padded interior.',
    images: ['https://picsum.photos/seed/helmet/800/800', 'https://picsum.photos/seed/helmet2/800/800', 'https://picsum.photos/seed/helmet3/800/800'],
    specifications: {
      Material: 'Fiberglass, Metal',
      Weight: '2.5kg',
      'Includes': 'Display Stand',
    },
    stock: 5,
  },
  {
    id: '4',
    name: 'Time-Traveling Car Model',
    category: 'Movie Memorabilia',
    price: 79.99,
    description: 'A 1:24 scale die-cast model of the famous time-traveling sports car. Features opening gull-wing doors and incredible detail.',
    images: ['https://picsum.photos/seed/car/800/800', 'https://picsum.photos/seed/car2/800/800'],
    specifications: {
      Material: 'Die-cast Metal',
      'Scale': '1:24',
      'Brand': 'Timeless Replicas',
    },
    stock: 25,
  },
  {
    id: '5',
    name: '"Cyber-Ronin" Graphic Tee',
    category: 'Clothing',
    price: 39.99,
    description: 'A comfortable and stylish graphic tee featuring a futuristic take on a classic samurai warrior. Made from 100% premium cotton.',
    images: ['https://picsum.photos/seed/tee/800/800', 'https://picsum.photos/seed/tee2/800/800'],
    specifications: {
      Material: '100% Cotton',
      'Fit': 'Regular',
      'Print': 'High-density screen print',
    },
    stock: 50,
  },
  {
    id: '6',
    name: 'Nostromo Crew Jacket',
    category: 'Clothing',
    price: 149.99,
    description: 'An authentic replica of the crew jackets worn aboard the USCSS Nostromo. Features embroidered patches and a durable, insulated design.',
    images: ['https://picsum.photos/seed/jacket/800/800', 'https://picsum.photos/seed/jacket2/800/800'],
    specifications: {
      Material: 'Nylon, Polyester lining',
      'Features': 'Embroidered patches, quilted lining',
      'Color': 'Vintage Green',
    },
    stock: 20,
  },
  {
    id: '7',
    name: 'Explorer\'s Satchel',
    category: 'Bags',
    price: 189.99,
    description: 'A rugged and stylish leather satchel inspired by the adventures of a legendary archaeologist. Perfect for daily use or your next expedition.',
    images: ['https://picsum.photos/seed/satchel/800/800', 'https://picsum.photos/seed/satchel2/800/800'],
    specifications: {
      Material: 'Full-grain leather, Brass hardware',
      'Dimensions': '15" x 11" x 4"',
      'Strap': 'Adjustable shoulder strap',
    },
    stock: 12,
  },
  {
    id: '8',
    name: 'Tech-Ninja Sling Bag',
    category: 'Bags',
    price: 99.99,
    description: 'A futuristic sling bag with multiple compartments and a water-resistant shell. Ideal for the urban commuter with a techwear aesthetic.',
    images: ['https://picsum.photos/seed/sling/800/800', 'https://picsum.photos/seed/sling2/800/800'],
    specifications: {
      Material: 'Ballistic Nylon',
      'Features': 'Magnetic buckle, USB pass-through',
      'Capacity': '10L',
    },
    stock: 40,
  },
];
